import type { CollectionConfig } from 'payload'

export const Projects: CollectionConfig = {
  slug: 'projects',
  admin: { useAsTitle: 'title', defaultColumns: ['id', 'name', 'country', 'category', 'status'] },
  fields: [
    { name: 'projectId', type: 'text', required: true, label: 'ID (ej. TVH-GT-0012)' },
    { name: 'name', type: 'text', required: true, label: 'Nombre corto' },
    { name: 'country', type: 'text', required: true, label: 'País' },
    { name: 'image', type: 'text', label: 'URL de imagen' },
    { name: 'category', type: 'select', required: true, label: 'Categoría', options: ['Bosques y Costas', 'Biodiversidad', 'Agricultura', 'Eficiencia'] },
    { name: 'riskRating', type: 'select', label: 'Nivel de Riesgo', options: ['Muy Bajo', 'Bajo', 'Medio', 'Alto'] },
    { name: 'eligibility', type: 'text', label: 'Estándar de Elegibilidad' },
    { name: 'credits', type: 'number', label: 'Créditos tCO₂e' },
    { name: 'pending', type: 'number', label: 'Pendientes' },
    { name: 'projectCount', type: 'number', label: 'Nº proyectos' },
    { name: 'shortDescription', type: 'textarea', label: 'Descripción corta' },
    { name: 'title', type: 'text', required: true, label: 'Título completo' },
    { name: 'prestatario', type: 'text', label: 'Prestatario' },
    { name: 'ejecutor', type: 'text', label: 'Ejecutor' },
    { name: 'status', type: 'select', label: 'Estado', options: ['En ejecución', 'Aprobado', 'Cerrado'] },
    { name: 'approved', type: 'text', label: 'Monto Aprobado (texto)' },
    { name: 'approvedUSD', type: 'number', label: 'Aprobado USD' },
    { name: 'disbursed', type: 'text', label: 'Desembolsado (texto)' },
    { name: 'disbursedUSD', type: 'number', label: 'Desembolsado USD' },
    { name: 'disbursedPct', type: 'number', label: 'Desembolsado %' },
    { name: 'cofinancier', type: 'text', label: 'Cofinanciador' },
    { name: 'approvalDate', type: 'text', label: 'Fecha Aprobación' },
    { name: 'startDate', type: 'text', label: 'Fecha Inicio' },
    { name: 'estimatedClose', type: 'text', label: 'Cierre Estimado' },
    { name: 'beneficiariesDirect', type: 'text', label: 'Beneficiarios Directos' },
    { name: 'beneficiariesIndirect', type: 'text', label: 'Beneficiarios Indirectos' },
    { name: 'objective', type: 'textarea', label: 'Objetivo General' },
    { name: 'objectives', type: 'array', label: 'Objetivos Específicos', fields: [{ name: 'text', type: 'text' }] },
    { name: 'results', type: 'array', label: 'Resultados', fields: [{ name: 'text', type: 'text' }] },
    { name: 'milestones', type: 'array', label: 'Hitos', fields: [
      { name: 'label', type: 'text' },
      { name: 'date', type: 'text' },
      { name: 'status', type: 'select', options: ['done', 'active', 'pending'] },
    ]},
    { name: 'disbursements', type: 'array', label: 'Desembolsos', fields: [
      { name: 'period', type: 'text' },
      { name: 'amount', type: 'number' },
    ]},
    { name: 'documents', type: 'array', label: 'Documentos', fields: [
      { name: 'name', type: 'text' },
      { name: 'type', type: 'text' },
      { name: 'size', type: 'text' },
      { name: 'date', type: 'text' },
    ]},
  ],
}
